name: http_logger
description: A logging middleware for Dart's http module.
version: 1.0.1

dependencies:
  http_middleware:
    git:
      url: git://github.com/joydeepsaha05/http_middleware.git
      ref: updated-dependencies

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
